"""Reservation user booker

Revision ID: 0a30746e80b3
Revises: a4317ca7a240
Create Date: 2026-01-28 14:53:54.834055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a30746e80b3'
down_revision: Union[str, Sequence[str], None] = 'a4317ca7a240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengernamerecord', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_passengernamerecord_user_id_users'), 'passengernamerecord', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_passengernamerecord_user_id_users'), 'passengernamerecord', type_='foreignkey')
    op.drop_column('passengernamerecord', 'user_id')
    # ### end Alembic commands ###
