"""Flight reservations

Revision ID: 579ecbe8b795
Revises: b16f00124ec3
Create Date: 2026-01-27 20:16:26.650040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '579ecbe8b795'
down_revision: Union[str, Sequence[str], None] = 'b16f00124ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengernamerecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seat_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticket_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticket_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('fk_passengernamerecord_flight_id_flight')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passengernamerecord'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengernamerecord')
    # ### end Alembic commands ###
