"""Reintroduce the M2M btw User and Ailrline

Revision ID: 6b40f5d4614a
Revises: a0bed39fa093
Create Date: 2026-01-15 13:24:28.066189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b40f5d4614a'
down_revision: Union[str, Sequence[str], None] = 'a0bed39fa093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlineadminlink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='admin_status'), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], name=op.f('fk_airlineadminlink_airline_id_airline')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_airlineadminlink_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'airline_id', name=op.f('pk_airlineadminlink'))
    )
    op.drop_constraint(op.f('fk_airline_admin_id_users'), 'airline', type_='foreignkey')
    op.drop_column('airline', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_airline_admin_id_users'), 'airline', 'users', ['admin_id'], ['id'])
    op.drop_table('airlineadminlink')
    # ### end Alembic commands ###
