"""Drop Link table

Revision ID: 72c4d52a44d0
Revises: 9096ec9e1fd8
Create Date: 2026-01-14 17:37:38.888274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72c4d52a44d0'
down_revision: Union[str, Sequence[str], None] = '9096ec9e1fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airline_admin_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline_admin_link',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('airline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], name=op.f('fk_airline_admin_link_airline_id_airline')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_airline_admin_link_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'airline_id', name=op.f('pk_airline_admin_link'))
    )
    # ### end Alembic commands ###
