"""Convert M2M to FK between Airline and User

Revision ID: 9096ec9e1fd8
Revises: 36038ca148d5
Create Date: 2026-01-14 17:33:49.829627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9096ec9e1fd8'
down_revision: Union[str, Sequence[str], None] = '36038ca148d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_airline_admin_id_users'), 'airline', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_airline_admin_id_users'), 'airline', type_='foreignkey')
    op.drop_column('airline', 'admin_id')
    # ### end Alembic commands ###
