"""Major refactor

Revision ID: a1a716248018
Revises: 
Create Date: 2026-01-14 08:51:53.573530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1a716248018'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icao_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airline')),
    sa.UniqueConstraint('contact_phone', name=op.f('uq_airline_contact_phone')),
    sa.UniqueConstraint('email', name=op.f('uq_airline_email')),
    sa.UniqueConstraint('icao_code', name=op.f('uq_airline_icao_code'))
    )
    op.create_index(op.f('ix_airline_airline_name'), 'airline', ['airline_name'], unique=True)
    op.create_table('airport',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('airport_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iata_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airport'))
    )
    op.create_index(op.f('ix_airport_airport_name'), 'airport', ['airport_name'], unique=True)
    op.create_index(op.f('ix_airport_iata_code'), 'airport', ['iata_code'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('airline_admin_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], name=op.f('fk_airline_admin_link_airline_id_airline')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_airline_admin_link_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'airline_id', name=op.f('pk_airline_admin_link'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airline_admin_link')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_airport_iata_code'), table_name='airport')
    op.drop_index(op.f('ix_airport_airport_name'), table_name='airport')
    op.drop_table('airport')
    op.drop_index(op.f('ix_airline_airline_name'), table_name='airline')
    op.drop_table('airline')
    # ### end Alembic commands ###
