"""Flight model and table creation

Revision ID: a39c741d88fb
Revises: 6b40f5d4614a
Create Date: 2026-01-26 23:45:08.681235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a39c741d88fb'
down_revision: Union[str, Sequence[str], None] = '6b40f5d4614a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.Column('flight_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('departure_port_id', sa.Integer(), nullable=True),
    sa.Column('destination_port_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], name=op.f('fk_flight_airline_id_airline')),
    sa.ForeignKeyConstraint(['departure_port_id'], ['airport.id'], name=op.f('fk_flight_departure_port_id_airport')),
    sa.ForeignKeyConstraint(['destination_port_id'], ['airport.id'], name=op.f('fk_flight_destination_port_id_airport')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
