"""Flight fare field

Revision ID: a4317ca7a240
Revises: 579ecbe8b795
Create Date: 2026-01-28 07:39:08.734749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4317ca7a240'
down_revision: Union[str, Sequence[str], None] = '579ecbe8b795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('airfare', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'airfare')
    # ### end Alembic commands ###
