"""Flight seats

Revision ID: b16f00124ec3
Revises: a39c741d88fb
Create Date: 2026-01-27 13:59:41.861791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b16f00124ec3'
down_revision: Union[str, Sequence[str], None] = 'a39c741d88fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flightseat',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('fk_flightseat_flight_id_flight')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flightseat')),
    sa.UniqueConstraint('flight_id', 'seat_number', name='unique_flight_seat_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flightseat')
    # ### end Alembic commands ###
